spring.application.name=clippy

spring.config.import=optional:file:.env[.properties]

## App Config
app.base-url=http://localhost:8080
app.default-expiry-in-days=30
app.validate-original-url=true
app.page-size=10

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false